import { SessionProvider } from '<nextjs>/components/SessionProvider'
import { authOptions } from '<nextjs>/pages/api/auth/[...nextauth]'
import { getServerSession } from 'next-auth'
import 'tailwindcss/tailwind.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ): (
            <h1>hello</h1>
          )}

        </SessionProvider>
      </body> 
    </html>
  )
}
